volumes:
  database_volume_data:
    name: '${DATABASE_NAME}_pg_data'
services:
  database:
    container_name: '${APP_NAME}_db'
    image: postgres:16-bookworm
    env_file:
      - ./.env
    environment:
      POSTGRES_USER: '${DATABASE_USERNAME}'
      POSTGRES_PASSWORD: '${DATABASE_PASSWORD}'
      POSTGRES_DB: '${DATABASE_NAME}'
    ports:
      - '${DATABASE_PORT}:5432'
    restart: 'unless-stopped'
    volumes:
      - ../${APP_NAME}_pg_data:/var/lib/postgresql/data
      # - ../data/postgres/initdb.d:/docker-entrypoint-initdb.d

  minio:
    container_name: '${APP_NAME}_minio'
    image: quay.io/minio/minio:RELEASE.2022-02-18T01-50-10Z
    volumes:
      - ../minio_data:/data
    ports:
      - ${MINIO_PORT}:${MINIO_PORT}
      - ${MINIO_CONSOLE_PORT}:${MINIO_CONSOLE_PORT}
    environment:
      MINIO_ROOT_USER: '${MINIO_ROOT_USER}'
      MINIO_ROOT_PASSWORD: '${MINIO_ROOT_PASSWORD}'
      MINIO_ADDRESS: ':${MINIO_PORT}'
      MINIO_CONSOLE_ADDRESS: ':${MINIO_CONSOLE_PORT}'
    restart: 'unless-stopped'
    command: minio server /data
